checkout-fees-for-woocommerce/includes/class-wc-checkout-fees.php, checkout-fees-for-woocommerce/includes/settings/class-wc-checkout-fees-meta-boxes-per-product.php, checkout-fees-for-woocommerce/includes/settings/class-wc-checkout-fees-settings-gateways.php, checkout-fees-for-woocommerce/uninstall.php
=> Fixes 2.5.8

checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php, checkout-fees-for-woocommerce/readme.txt
Updated
1. Version number
2. Changelog
3. Tested up to values
=> Version 2.5.8

checkout-fees-for-woocommerce/includes/class-wc-checkout-fees.php
=> Fixes 2 5 9

checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php, checkout-fees-for-woocommerce/readme.txt
Updated
1. Version number
2. WC tested up value
3. Readme file.
=> Version 2.5.9

checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php, checkout-fees-for-woocommerce/includes/settings/class-wc-checkout-fees-settings-gateways.php
Added utm tags to all the upgrade to pro links in the settings and the 'Unlock All' option.
=> Add UTM tags to all upgrade links

checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php, checkout-fees-for-woocommerce/includes/class-wc-checkout-fees-admin.php, checkout-fees-for-woocommerce/includes/class-wc-checkout-fees-args.php, checkout-fees-for-woocommerce/includes/class-wc-checkout-fees-info.php, checkout-fees-for-woocommerce/includes/class-wc-checkout-fees.php, checkout-fees-for-woocommerce/includes/functions/country-functions.php, checkout-fees-for-woocommerce/includes/settings/class-wc-checkout-fees-meta-boxes-per-product.php, checkout-fees-for-woocommerce/includes/settings/class-wc-checkout-fees-settings-gateways.php, checkout-fees-for-woocommerce/includes/settings/class-wc-checkout-fees-settings-general.php, checkout-fees-for-woocommerce/includes/settings/class-wc-checkout-fees-settings-global-extra-fee.php, checkout-fees-for-woocommerce/includes/settings/class-wc-checkout-fees-settings-info.php, checkout-fees-for-woocommerce/includes/settings/class-wc-checkout-fees-settings-section.php, checkout-fees-for-woocommerce/includes/settings/class-wc-settings-checkout-fees.php, checkout-fees-for-woocommerce/uninstall.php
Made changes in the plugin related to phpcs errors and optimzed the code.
=> Phpcs changes for the plugin

checkout-fees-for-woocommerce/includes/class-wc-checkout-fees-admin.php, checkout-fees-for-woocommerce/includes/class-wc-checkout-fees-args.php, checkout-fees-for-woocommerce/includes/class-wc-checkout-fees-info.php, checkout-fees-for-woocommerce/includes/class-wc-checkout-fees.php
Fix the package name in the 4 files.
=> Fix the package name for the files

checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php, checkout-fees-for-woocommerce/readme.txt
Version 2.6 :
* Made the plugin code compliant with WPCS standards.
* Added UTM tags for the Pro plugin links.
=> Version 2.6

checkout-fees-for-woocommerce/readme.txt
Added all other Pro & Free plugins to the page. Updated stable tag to Trunk.
=> Updating readme file

checkout-fees-for-woocommerce/readme.txt
Added missing plugin of Print invoice in free plugins list
=> Added missing plugin of Print invoice in free plugins list

checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php, checkout-fees-for-woocommerce/readme.txt
Updated tested up to values and readme
=> Version 2.6.1

checkout-fees-for-woocommerce/readme.txt
Updated readme.txt file for WP5.5 compatibility
=> Updated readme.txt file for WP5.5 compatibility

checkout-fees-for-woocommerce/includes/class-alg-wc-checkout-fees.php
Error was coming in the debug log. This is fixed now.
Fixes #41
=> Error was coming in the debug log.

checkout-fees-for-woocommerce/includes/class-alg-wc-checkout-fees.php, checkout-fees-for-woocommerce/langs/checkout-fees-for-woocommerce.pot
Include string was not translated and Tax label was not coming. This is fixed now
Fixes #15
=> Include string was not translated and Tax label was not coming.

checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php, checkout-fees-for-woocommerce/readme.txt
=> Version 2.6.2

checkout-fees-for-woocommerce/includes/class-alg-wc-checkout-fees.php
No Gateway fees/discount will not be added if PW gift card is applied to the cart.
Fixes #48
=> Gateway fees will not be added if PW gift card is applied to the cart

checkout-fees-for-woocommerce/readme.txt
Updated WP tested upto tag in readme file for WP5.7
=> WP tested upto 5.7

checkout-fees-for-woocommerce/includes/settings/class-alg-wc-checkout-fees-settings-gateways.php
Error were coming in debug log. This is fixed now.
Fixes #66
=> Debug log error

checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php, checkout-fees-for-woocommerce/readme.txt
=> version 2.7.0

includes/class-alg-wc-checkout-fees-admin.php
=> Fixed conflict with Byka Cash

includes/js/checkout-fees.js
=> Apply Clients suggestion

checkout-fees-for-woocommerce.php, includes/class-alg-wc-checkout-fees-admin.php, includes/class-alg-wc-checkout-fees.php, includes/class-alg-wc-order-fees.php, includes/settings/class-alg-wc-checkout-fees-settings-general.php, includes/settings/class-alg-wc-checkout-fees-settings-global-extra-fee.php, includes/settings/class-alg-wc-checkout-fees-settings-info.php, includes/settings/class-alg-wc-checkout-fees-settings-per-product.php, includes/settings/class-alg-wc-settings-checkout-fees.php
=> Fixed following error message with PHP 8.2.4

checkout-fees-for-woocommerce.php, readme.txt
1. Update the plugin version number. 
2. Added the changelog.
=> Version 2.10.0

checkout-fees-for-woocommerce.php, readme.txt
1. Change Wp Tested up version in changelog.txt file. 
2. Change Wc Tested version in main plugin file.
=> Change-wp-wc-version-2.10.0

checkout-fees-for-woocommerce.php, readme.txt
1. Update the plugin version number. 
2. Added the changelog.
=> Version 2.10.1

includes/class-alg-wc-order-fees.php
Fixed live git copy error class utills already in used
=> Fix #118, #157 - conflict

includes/class-alg-wc-checkout-fees.php
=> ReFix #167

includes/class-alg-wc-checkout-fees.php, includes/class-alg-wc-order-fees.php
Fixed issue got during testing time related to general option & some mathamatical calculation issue fix-testing-issue
=> fix-testing-issue

includes/class-alg-wc-checkout-fees.php, includes/class-alg-wc-order-fees.php
Reverts TycheSoftwares/checkout-fees-for-woocommerce#175
=> Revert "refix-16"

includes/class-alg-wc-checkout-fees.php, includes/settings/class-alg-wc-checkout-fees-settings-global-extra-fee.php
Reverts TycheSoftwares/checkout-fees-for-woocommerce#172
=> Revert "fix #16"

checkout-fees-for-woocommerce.php, readme.txt
1) Change version in plugin file 2) Add chnagelog in readme file Final v.2.10.3
=> final-2.10.3

includes/class-alg-wc-checkout-fees.php
=> Fixed issue with Minus Sign Placement in Payment Gateway Discount

checkout-fees-for-woocommerce.php
1) Fixed Version related log file error 
2) Remove enqueue tyche.js file function because it was already enqueued in file class-alg-wc-checkout-fees-admin.php on line number 57.
=> Fix-Version-Log-Error

checkout-fees-for-woocommerce.php, readme.txt
1) Change version in readme file. 
2) Add log to the readme file. 
3) Change version in plugin file final-2.11.0.
=> final-2.11.0

checkout-fees-for-woocommerce.php, includes/component/plugin-tracking/class-tyche-plugin-tracking.php, includes/js/tyche-dismiss-tracking-notice.js
changed 'ts_tracker_data' filter
=> Fixed tracking changes

checkout-fees-for-woocommerce.php, readme.txt
Fix #v-2.12.0 1) Add the changelog in readme file 2) Change wc & wp tested up version in plugin main file v.2.12.0.
=> Fix-#v-2.12.0

readme.txt
=> Updated readme.txt file

includes/component/plugin-tracking/class-tyche-plugin-tracking.php
Fixed vulnerability for dismiss notice
=> Added permission/role checks on dismiss notice.

checkout-fees-for-woocommerce.php, readme.txt
=> Updated version into v2.12.1

includes/component/plugin-tracking/class-tyche-plugin-tracking.php
Dismissing Notices - Implementing nonce check as well as permission/role based on this security report:  [This Patchstack report](https://patchstack.com/database/report-preview/e6c07109-98f5-4411-aee3-d20efed950b7?pin=dFV4Lbv3vSS842t0)
Added the user to be logged in and permission check and nonce before the action can be executed.
=> Fixed security nonce

checkout-fees-for-woocommerce.php, readme.txt
=> Updated version into 2.12.2

checkout-fees-for-woocommerce.php, includes/settings/class-alg-wc-settings-checkout-fees.php
=> Fixed Vulnerable to Broken Access Control

checkout-fees-for-woocommerce.php, readme.txt
=> Updated version into 2.13.0

includes/js/checkout-fees.js
Fix #248 Compatibility issue with WooCommerce Authorize.Net Gateway plugin.
=> Fix #248 Compatibility issue with WooCommerce Authorize.Net Gateway plugin.

checkout-fees-for-woocommerce.php, readme.txt
=> version change to 2.14.0

includes/class-alg-wc-all-component.php, includes/component/plugin-deactivation/class-tyche-plugin-deactivation.php, includes/js/tyche.js
deactivation changes version update deactivation and tyche.js
=> deactivation changes

checkout-fees-for-woocommerce.php, readme.txt
=> version update redme changes

includes/settings/class-alg-wc-checkout-fees-settings-general.php, includes/settings/class-alg-wc-checkout-fees-settings-global-extra-fee.php, includes/settings/class-alg-wc-checkout-fees-settings-info.php, includes/settings/class-alg-wc-checkout-fees-settings-per-product.php
=> Fix #255 translation fixed

includes/class-alg-wc-checkout-fees.php
=> Fix #262 PHP Deprecated Error

includes/class-alg-wc-checkout-fees.php
Fix #260 everypay fees is not showing on checkout page.
=> Fix #260 everypay fees is not showing on checkout page.

includes/settings/class-alg-wc-checkout-fees-settings-gateways.php, includes/settings/class-alg-wc-checkout-fees-settings-per-product.php
Fix #266 woo payment gatways title are not fetching
=> Fix #266 woo payment gatways name are not fetching

changelog.txt, checkout-fees-for-woocommerce.php, readme.txt
Version change to 2.16.0 added changelog
=> Version change to 2.16.0

includes/class-alg-wc-order-fees.php
Fix #275 Fees are adding again on pay for order page.
=> Fix #275 Fees are adding again on pay for order page.

includes/settings/class-alg-wc-settings-checkout-fees.php
Fix #271 reset section is not working for gateways page.
=> Fix #271 reset section is not working for gateways page

includes/class-alg-wc-order-fees.php
Fix #275 when empty title fee is added. it is adding again on this function.
=> Fix #275 when empty title fee is added. it is adding again on this function.

changelog.txt, checkout-fees-for-woocommerce.php, readme.txt
=> version change pr - 2.17.0

includes/settings/class-alg-wc-checkout-fees-settings-gateways.php, includes/settings/class-alg-wc-checkout-fees-settings-per-product.php
=> fix #284 added gatway title.
